---
title: "Japanese Population"
author: "guchiguchi"
date: "2018/6/9"
output: slidy_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Summary

- This presentation shows you about Japanese population.
- Japan is aging ever faster.
- It is said that Japanese population is decreasing.
- But some area, mainly in large cities, is increasing population.


## R Code
  
```
#library
library(dplyr)
library(ggplot2)
library(scales)

#data 
JapanesePopulation <- readRDS("japanesepopulation/data/JapanesePopulation.rds")


JapanesePopulation %>% 
  filter(AREA == "All Japan") %>% 
  select(year, Population) -> ggplot_data 
```
data is in my [repo](https://github.com/guchiguchi/course9_Shiny_Application_and_Reproducible_Pitch/blob/master/data/JapanesePopulation.rds)

## Increasing Area
```{r message=FALSE, warning=FALSE}
library(dplyr)
library(ggplot2)
library(scales)

JapanesePopulation <- readRDS("japanesepopulation/data/JapanesePopulation.rds")
JapanesePopulation %>% filter(AREA == "All Japan") %>% select(year, Population) -> ggplot_data 
```

### Tokyo
```{r fig2, fig.height = 3, fig.width = 13, fig.align = "center"}
JapanesePopulation %>% filter(AREA == "Tokyo-to") %>% select(year, Population) -> ggplot_data
ggplot_data %>% 
  ggplot(aes(x = year, y = Population)) + 
  geom_bar(stat = "identity", fill =  "skyblue")+
  scale_y_continuous(labels = comma)
```

### Kanagawa
```{r fig3, fig.height = 3, fig.width = 13, fig.align = "center"}
JapanesePopulation %>% filter(AREA == "Kanagawa-ken") %>% select(year, Population) -> ggplot_data
ggplot_data %>% 
  ggplot(aes(x = year, y = Population)) + 
  geom_bar(stat = "identity", fill =  "skyblue")+
  scale_y_continuous(labels = comma)
```

## Decreasing Area

###Hokkaido 
```{r fig4, fig.height = 3, fig.width = 13, fig.align = "center"}
JapanesePopulation %>% filter(AREA == "Hokkaido") %>% select(year, Population) -> ggplot_data
ggplot_data %>% 
  ggplot(aes(x = year, y = Population)) + 
  geom_bar(stat = "identity", fill =  "blue")+
  scale_y_continuous(labels = comma)
```


###Tottori-ken
```{r fig5, fig.height = 3, fig.width = 13, fig.align = "center"}
JapanesePopulation %>% filter(AREA == "Tottori-ken") %>% select(year, Population) -> ggplot_data
ggplot_data %>% 
  ggplot(aes(x = year, y = Population)) + 
  geom_bar(stat = "identity", fill =  "blue")+
  scale_y_continuous(labels = comma)
```


## Thank you!!

###This is [my app](https://guchiguchi.shinyapps.io/japanesepopulation/). Please check it!!









